### ISSUE TITLE
[ORDER-011] 주문 결재 요청 취소

### ISSUE THREAD

**Issue by Yong-ga-ri** [variety-crew/brewnet-app#14]
# 제목
주문 결재 요청 취소

## 설명
- 주문 결재 요청(주문 요청서)을 반려한다

1. 관리자 전결: 관리자에게 '전결' 권한이 있는 경우, 관리자가 주문 결재 요청을 반려한다 <X>
2. 책임자 결재: 관리자에게 '전결' 권한이 없는 경우, 책임자가 주문 결재 요청을 반려한다
3. 책임자 결재: 담당자에게 '결재/전결'권한이 있고, 책임자의 결재를 받아야 하는 경우, 책임자가 주문 결재 요청을 승인한다

## TODO
- [ ] 책임자 결재: 관리자에게 '전결' 권한이 없는 경우, 책임자가 주문 결재 요청을 반려한다
- [ ] 책임자 결재: 담당자에게 '결재/전결'권한이 있고, 책임자의 결재를 받아야 하는 경우, 책임자가 주문 결재 요청을 승인한다

## 세부 개발 요구 사항
- [ ] 책임자 결재: 관리자에게 '전결' 권한이 없는 경우, 책임자가 주문 결재 요청을 반려한다
- [ ] 책임자 결재: 담당자에게 '결재/전결'권한이 있고, 책임자의 결재를 받아야 하는 경우, 책임자가 주문 결재 요청을 승인한다
