### ISSUE TITLE
[ORDER-001] 개발 대제목

### ISSUE THREAD

**Issue by Yong-ga-ri** [variety-crew/brewnet-app#4]
# 제목
주문 등록

## 설명
- 가맹점 관리자가 물품을 주문한다 (주문 등록)
- 시스템이 자동으로 주문 요청서를 생성한다

## TODO
- [ ] 주문 요청서
- [ ] (자동등록) 가맹점명, 주문일
- [ ] (선택)상품명, (입력)주문수량
- [ ] (자동계산)단가, 공급가액, 합계

## 세부 개발 요구 사항
-
