### ISSUE TITLE
[FRANCHISE-004] 가맹점 목록 조회

### ISSUE THREAD

**Issue by JeongJunSeo99** [variety-crew/brewnet-app#97]
# 제목
가맹점 목록 조회

## 설명
가맹점 목록을 조회한다
- 가맹점 위치 별 (도/특별시/광역시 단위)
- 지점 이름으로 검색 가능

## TODO
- [x] 가맹점 목록 조회
- [x] 가맹점 위치 별 필터링
- [x] 가맹점 지점 이름 검색
